apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petclinic-error-alert
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
spec:
  groups:
  - name: petclinic
    rules:
    - alert: HighErrorAlert
      expr: increase(logback_events_total{app="petclinic",level="error",runtime="springboot",}[1m]) > 4
      labels:
        severity: 'critical'
        app: petclinic
      annotations:
        summary: High error rate.
