apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petclinic-pod-restarts
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
spec:
  groups:
  - name: petclinic
    rules:
    - alert: HighPodRestarts
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 1
      labels:
        severity: 'critical'
        app: petclinic
      annotations:
        summary: High Pod restart rate.
