apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server
spec:
  endpoints:
  - path: /q/metrics
    port: 8080-tcp
    scheme: http
  selector:
    matchLabels:
      prometheus-metrics: "true"
