apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workload-monitoring

resources:
  - session-secret.yaml
  - grafana-proxy-rbac.yaml
  - cluster-monitor-view-rb.yaml
  - grafana-ds.yaml
  - grafana.yaml
  - patch-grafana-ds-sa.yaml
  - patch-grafana-ds-job.yaml
